### ISSUE TITLE
#Dimensions do not match

### ISSUE THREAD

**Issue by zhaojintang** [Franfee/Python-CTRV-simulation#1]
Hello, when I run your code, in MainCTRV
The following error occurred on line 153 of the .py file. How did you solve it?
P = np.matmul(np.matmul(JA, P), JA.T) + Q
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 1)

**Comment by Franfee** [comment]
The shape of the state space (JA) should be [5X5], numdifftools calculates the shape as [1X5X5]. Sorry, I lost the version I was using before, you can use numdifftools==0.6.0, but then you will get a warning about numerical calculations, you can also handle the dimensions yourself.
